<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFu2kins\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFu2kins/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFu2kins.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFu2kins\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFu2kins\appProdProjectContainer([
    'container.build_hash' => 'Fu2kins',
    'container.build_id' => 'c5401b14',
    'container.build_time' => 1611259719,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFu2kins');
